from qtpy import QtCore, QtWidgets

class Ui_SecurePasswordChangeDialog(object):
    def setupUi(self, SecurePasswordChangeDialog):
        SecurePasswordChangeDialog.setObjectName("SecurePasswordChangeDialog")
        SecurePasswordChangeDialog.resize(173, 170)
        self.verticalLayout = QtWidgets.QVBoxLayout(SecurePasswordChangeDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.oldPasswordField = QtWidgets.QLineEdit(SecurePasswordChangeDialog)
        self.oldPasswordField.setEchoMode(QtWidgets.QLineEdit.Password)
        self.oldPasswordField.setObjectName("oldPasswordField")
        self.verticalLayout.addWidget(self.oldPasswordField)
        self.newPasswordField = QtWidgets.QLineEdit(SecurePasswordChangeDialog)
        self.newPasswordField.setEchoMode(QtWidgets.QLineEdit.Password)
        self.newPasswordField.setObjectName("newPasswordField")
        self.verticalLayout.addWidget(self.newPasswordField)
        self.confirmPasswordField = QtWidgets.QLineEdit(SecurePasswordChangeDialog)
        self.confirmPasswordField.setEchoMode(QtWidgets.QLineEdit.Password)
        self.confirmPasswordField.setObjectName("confirmPasswordField")
        self.verticalLayout.addWidget(self.confirmPasswordField)
        self.updateBackupCodesCheckbox = QtWidgets.QCheckBox(SecurePasswordChangeDialog)
        self.updateBackupCodesCheckbox.setObjectName("updateBackupCodesCheckbox")
        self.verticalLayout.addWidget(self.updateBackupCodesCheckbox)
        self.updateRecoveryKeyCheckbox = QtWidgets.QCheckBox(SecurePasswordChangeDialog)
        self.updateRecoveryKeyCheckbox.setObjectName("updateRecoveryKeyCheckbox")
        self.verticalLayout.addWidget(self.updateRecoveryKeyCheckbox)
        self.rotateSaltCheckbox = QtWidgets.QCheckBox(SecurePasswordChangeDialog)
        self.rotateSaltCheckbox.setObjectName("rotateSaltCheckbox")
        self.verticalLayout.addWidget(self.rotateSaltCheckbox)
        self.widget = QtWidgets.QWidget(SecurePasswordChangeDialog)
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.ok = QtWidgets.QPushButton(self.widget)
        self.ok.setObjectName("ok")
        self.horizontalLayout.addWidget(self.ok)
        self.cancel = QtWidgets.QPushButton(self.widget)
        self.cancel.setObjectName("cancel")
        self.horizontalLayout.addWidget(self.cancel)
        self.verticalLayout.addWidget(self.widget)

        self.retranslateUi(SecurePasswordChangeDialog)
        QtCore.QMetaObject.connectSlotsByName(SecurePasswordChangeDialog)

    def retranslateUi(self, SecurePasswordChangeDialog):
        _translate = QtCore.QCoreApplication.translate
        SecurePasswordChangeDialog.setWindowTitle(_translate("SecurePasswordChangeDialog", self.tr("Secure Password Change")))
        self.oldPasswordField.setPlaceholderText(_translate("SecurePasswordChangeDialog", self.tr("Old Password")))
        self.newPasswordField.setPlaceholderText(_translate("SecurePasswordChangeDialog", self.tr("New Password")))
        self.confirmPasswordField.setPlaceholderText(_translate("SecurePasswordChangeDialog", self.tr("Confirm Password")))
        self.updateBackupCodesCheckbox.setText(_translate("SecurePasswordChangeDialog", self.tr("Regenerate Backup Codes")))
        self.updateRecoveryKeyCheckbox.setText(_translate("SecurePasswordChangeDialog", self.tr("Regenerate Recovery Key")))
        self.rotateSaltCheckbox.setToolTip(_translate("SecurePasswordChangeDialog", self.tr("Replaces your cryptographic salt. Vault will be re-encrypted. For advanced security hygiene.")))
        self.rotateSaltCheckbox.setText(_translate("SecurePasswordChangeDialog", self.tr("Rotate salt and rewrap vault (advanced)")))
        self.ok.setText(_translate("SecurePasswordChangeDialog", self.tr("OK")))
        self.cancel.setText(_translate("SecurePasswordChangeDialog", self.tr("Cancel")))
