from qtpy import QtCore, QtWidgets

class Ui_ForgotPasswordDialog(object):
    def setupUi(self, ForgotPasswordDialog):
        ForgotPasswordDialog.setObjectName("ForgotPasswordDialog")
        ForgotPasswordDialog.resize(312, 210)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(ForgotPasswordDialog.sizePolicy().hasHeightForWidth())
        ForgotPasswordDialog.setSizePolicy(sizePolicy)
        self.verticalLayout = QtWidgets.QVBoxLayout(ForgotPasswordDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.usernameField = QtWidgets.QLineEdit(ForgotPasswordDialog)
        self.usernameField.setObjectName("usernameField")
        self.verticalLayout.addWidget(self.usernameField)
        self.recoveryKeyField = QtWidgets.QLineEdit(ForgotPasswordDialog)
        self.recoveryKeyField.setObjectName("recoveryKeyField")
        self.verticalLayout.addWidget(self.recoveryKeyField)
        self.newPasswordField = QtWidgets.QLineEdit(ForgotPasswordDialog)
        self.newPasswordField.setEchoMode(QtWidgets.QLineEdit.Password)
        self.newPasswordField.setObjectName("newPasswordField")
        self.verticalLayout.addWidget(self.newPasswordField)
        self.confirmPasswordField = QtWidgets.QLineEdit(ForgotPasswordDialog)
        self.confirmPasswordField.setEchoMode(QtWidgets.QLineEdit.Password)
        self.confirmPasswordField.setObjectName("confirmPasswordField")
        self.verticalLayout.addWidget(self.confirmPasswordField)
        self.password_generator_1 = QtWidgets.QPushButton(ForgotPasswordDialog)
        self.password_generator_1.setObjectName("password_generator_1")
        self.verticalLayout.addWidget(self.password_generator_1)
        self.passwordInfoLabel = QtWidgets.QLabel(ForgotPasswordDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.passwordInfoLabel.sizePolicy().hasHeightForWidth())
        self.passwordInfoLabel.setSizePolicy(sizePolicy)
        self.passwordInfoLabel.setMinimumSize(QtCore.QSize(0, 0))
        self.passwordInfoLabel.setMaximumSize(QtCore.QSize(5888, 5999))
        self.passwordInfoLabel.setStyleSheet("color: gray; font-size: 10pt;")
        self.passwordInfoLabel.setScaledContents(True)
        self.passwordInfoLabel.setWordWrap(True)
        self.passwordInfoLabel.setObjectName("passwordInfoLabel")
        self.verticalLayout.addWidget(self.passwordInfoLabel, 0, QtCore.Qt.AlignTop)
        self.buttonLayout = QtWidgets.QHBoxLayout()
        self.buttonLayout.setObjectName("buttonLayout")
        self.resetButton = QtWidgets.QPushButton(ForgotPasswordDialog)
        self.resetButton.setObjectName("resetButton")
        self.buttonLayout.addWidget(self.resetButton)
        self.cancelButton = QtWidgets.QPushButton(ForgotPasswordDialog)
        self.cancelButton.setObjectName("cancelButton")
        self.buttonLayout.addWidget(self.cancelButton)
        self.verticalLayout.addLayout(self.buttonLayout)

        self.retranslateUi(ForgotPasswordDialog)
        QtCore.QMetaObject.connectSlotsByName(ForgotPasswordDialog)

    def retranslateUi(self, ForgotPasswordDialog):
        _translate = QtCore.QCoreApplication.translate
        ForgotPasswordDialog.setWindowTitle(_translate("ForgotPasswordDialog", self.tr("Forgot Password")))
        self.usernameField.setPlaceholderText(_translate("ForgotPasswordDialog", self.tr("Username")))
        self.recoveryKeyField.setPlaceholderText(_translate("ForgotPasswordDialog", self.tr("Recovery Key")))
        self.newPasswordField.setPlaceholderText(_translate("ForgotPasswordDialog", self.tr("New Password")))
        self.confirmPasswordField.setPlaceholderText(_translate("ForgotPasswordDialog", self.tr("Confirm New Password")))
        self.password_generator_1.setText(_translate("ForgotPasswordDialog", self.tr("Generate Password")))
        self.passwordInfoLabel.setText(_translate("ForgotPasswordDialog", self.tr("Password must be at least 8 characters long and include an uppercase letter,"
        " a lowercase letter, a number, and a symbol.")))
        self.resetButton.setText(_translate("ForgotPasswordDialog", self.tr("Reset Password")))
        self.cancelButton.setText(_translate("ForgotPasswordDialog", self.tr("Cancel")))
